#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'ssh2http'

unless ENV['SSH_CONNECTION']
  puts "Only ssh allowed"
  exit 1
end

Ssh2http.new(ENV['SSH_ORIGINAL_COMMAND']).run!
